-- DXY Research Platform V1/V2 schema for Supabase Postgres.
-- Import CSVs from data/v1 and data/v2 into these tables.

create table if not exists public.dxy_daily_v1 (
  full_date date primary key,
  year integer not null,
  month text not null,
  day text not null,
  date integer not null,
  d_range integer not null,
  d_close text not null check (d_close in ('bullish', 'bearish')),
  daily_profile text,
  w_close text not null check (w_close in ('bullish', 'bearish')),
  w_range integer not null,
  w_daily_match boolean not null,
  wh text not null,
  wl text not null,
  m_close text not null check (m_close in ('bullish', 'bearish')),
  m_d_match boolean not null,
  m_w_match boolean not null,
  event_week boolean default false,
  cpi_week boolean default false,
  nfp_week boolean default false,
  cpi_release_date_est date,
  nfp_release_date_est date,
  calendar_source text,
  source_symbol text default 'DX-Y.NYB',
  source_provider text default 'Yahoo Finance chart API',
  updated_at timestamptz not null default now()
);

create table if not exists public.dxy_daily_v2 (
  full_date date primary key,
  year integer not null,
  month text not null,
  month_number integer not null,
  day text not null,
  date integer not null,
  day_of_month integer not null,
  week_of_month integer not null,
  quarter integer not null,
  d_open numeric,
  d_high numeric,
  d_low numeric,
  d_close_price numeric,
  d_range integer not null,
  d_range_bucket text,
  d_close text not null check (d_close in ('bullish', 'bearish')),
  body_points integer,
  upper_wick_points integer,
  lower_wick_points integer,
  body_pct_of_range numeric,
  close_position_pct numeric,
  daily_profile text,
  prev_day_close text,
  prev_day_range integer,
  inside_day boolean,
  outside_day boolean,
  break_prev_day_high boolean,
  break_prev_day_low boolean,
  uup_open numeric,
  uup_high numeric,
  uup_low numeric,
  uup_close numeric,
  uup_volume bigint,
  volume_source text,
  week_id text not null,
  month_id text not null,
  w_close text not null check (w_close in ('bullish', 'bearish')),
  w_range integer not null,
  w_range_bucket text,
  w_daily_match boolean,
  wh text,
  wl text,
  m_close text not null check (m_close in ('bullish', 'bearish')),
  m_d_match boolean,
  m_w_match boolean,
  event_type text default 'normal',
  event_week boolean default false,
  cpi_week boolean default false,
  nfp_week boolean default false,
  cpi_release_date_est date,
  nfp_release_date_est date,
  calendar_source text,
  source_symbol text default 'DX-Y.NYB',
  source_provider text default 'Yahoo Finance chart API',
  updated_at timestamptz not null default now()
);

create table if not exists public.dxy_weekly_v2 (
  week_id text primary key,
  week_start date not null,
  week_end date not null,
  iso_year integer not null,
  iso_week integer not null,
  w_open numeric,
  w_high numeric,
  w_low numeric,
  w_close_price numeric,
  w_range integer not null,
  w_range_bucket text,
  w_close text not null check (w_close in ('bullish', 'bearish')),
  wh text,
  wl text,
  w_body_points integer,
  w_upper_wick_points integer,
  w_lower_wick_points integer,
  w_close_position_pct numeric,
  daily_bullish_count integer,
  daily_bearish_count integer,
  trading_days integer,
  uup_volume_sum bigint,
  uup_volume_avg bigint,
  prev_week_close text,
  prev_week_range integer,
  prev_week_range_bucket text,
  event_type text default 'normal',
  event_week boolean default false,
  cpi_week boolean default false,
  nfp_week boolean default false,
  cpi_release_date_est date,
  nfp_release_date_est date,
  calendar_source text,
  month_id text,
  m_close text,
  m_range integer,
  m_range_bucket text,
  updated_at timestamptz not null default now()
);

create table if not exists public.dxy_monthly_v2 (
  month_id text primary key,
  month_start date not null,
  month_end date not null,
  year integer not null,
  month text not null,
  month_number integer not null,
  m_open numeric,
  m_high numeric,
  m_low numeric,
  m_close_price numeric,
  m_range integer not null,
  m_range_bucket text,
  m_close text not null check (m_close in ('bullish', 'bearish')),
  weekly_bullish_count integer,
  weekly_bearish_count integer,
  trading_days integer,
  uup_volume_sum bigint,
  uup_volume_avg bigint,
  prev_month_close text,
  prev_month_range integer,
  prev_month_range_bucket text,
  updated_at timestamptz not null default now()
);

create table if not exists public.data_update_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null check (status in ('running', 'success', 'failed')),
  rows_inserted integer not null default 0,
  rows_updated integer not null default 0,
  latest_date date,
  error_message text
);

create index if not exists dxy_daily_v2_week_id_idx on public.dxy_daily_v2 (week_id);
create index if not exists dxy_daily_v2_month_id_idx on public.dxy_daily_v2 (month_id);
create index if not exists dxy_daily_v2_bias_idx on public.dxy_daily_v2 (d_close, w_close, m_close);
create index if not exists dxy_daily_v2_event_idx on public.dxy_daily_v2 (event_type, event_week, cpi_week, nfp_week);
create index if not exists dxy_weekly_v2_bias_idx on public.dxy_weekly_v2 (w_close, m_close, wh, wl);
create index if not exists dxy_weekly_v2_event_idx on public.dxy_weekly_v2 (event_type, event_week, cpi_week, nfp_week);
create index if not exists dxy_monthly_v2_bias_idx on public.dxy_monthly_v2 (m_close);

alter table public.dxy_daily_v1 enable row level security;
alter table public.dxy_daily_v2 enable row level security;
alter table public.dxy_weekly_v2 enable row level security;
alter table public.dxy_monthly_v2 enable row level security;
alter table public.data_update_runs enable row level security;

create policy "public read dxy_daily_v1" on public.dxy_daily_v1 for select to anon using (true);
create policy "public read dxy_daily_v2" on public.dxy_daily_v2 for select to anon using (true);
create policy "public read dxy_weekly_v2" on public.dxy_weekly_v2 for select to anon using (true);
create policy "public read dxy_monthly_v2" on public.dxy_monthly_v2 for select to anon using (true);
create policy "public read successful update runs" on public.data_update_runs for select to anon using (status = 'success');
